### ISSUE TITLE
New Tab Page Fails to Load Properly After Returning from Any Website

### ISSUE THREAD

**Issue by fr0st-iwnl** [maxhu08/mtab#27] opened 2024-08-09 19:32 UTC
# So i wanted to ask why is this happening?

## When I navigate to any website and then return to the new tab page, the homepage fails to load correctly. The UI elements are either missing or the page appears blank. Why does this happen?

`mtab version : 1.3.7`

https://github.com/user-attachments/assets/2c7e6440-4417-4e1e-87ba-260522763e72

**Comment by maxhu08** [comment] 2024-08-09 20:52
That's strange, this only happens on firefox so I've never noticed.

I'm going to try to figure this out.

**Comment by maxhu08** [comment] 2024-08-09 21:14
Strange, it suddenly stopped happening to me even though I didn't change anything, so I can't reproduce it anymore. 

I still tried to fix it, but I'm going to leave this issue open until it's completely fixed.

Hopefully this stops happening in the next release, but I can't know for sure.

**Comment by KLDv21** [comment] 2024-08-17 05:44
Still happening on v1.3.9

**Comment by maxhu08** [comment] 2024-08-18 20:22
This should be fixed now.

**Closed by maxhu08** 2024-08-18 20:22 UTC
