### ISSUE TITLE
Icon Glass Effect broken

### ISSUE THREAD

**Issue by Spoljarevic** [maxhu08/mtab#42] opened 2024-09-18 18:10 UTC
Hello,
when I open a new Tab with mtab, the first two Icons (Visible in Screenshot below) always have this weird cut in it.
This happened since I installed the add-on a few days ago.
After a reset, the problem remains.
I need to hover over it, then it goes away.
But after opening a new tab, the problem is back.

![image](https://github.com/user-attachments/assets/857d847e-9010-48b5-8bb1-e47aee137417)

**Comment by maxhu08** [comment] 2024-09-18 23:41
That's strange. I'm going to try to fix this soon.

**Comment by maxhu08** [comment] 2024-09-19 01:34
This seems to only happen on firefox, and I don't know why, so I'm not sure what to do.

Check if it works properly on chrome, not an ideal solution but I can't seem to find the reason behind this happens.

**Comment by shahiljain** [comment] 2024-09-23 06:32
I can't tell you why or how but the issue was there for me in the beginning but it is gone for me now. It could be that once you apply a custom wallpaper you must restart the browser. But even that, I tried to reset the wallpaper and change it, the issue is completely gone. Maybe it is a temporary bug. 

Hell I even uninstalled and reinstalled the extension, maybe a firefox update fixed it? BUT I didn't even get a firefox update.

**Comment by shahiljain** [comment] 2024-09-24 10:13
Hi, okay I figured it out, it was because I removed the search bar! Adding the search bar brings back the issue, I shall investigate this further.

**Comment by maxhu08** [comment] 2024-09-25 22:20
I honestly have no idea. This seems to only happen on firefox based browsers and it also only happens to the first two bookmarks which is really strange. 

Lowering the width of the window seems to prevent it but I'm not sure how I can fix it knowing that.

Still trying to think of a solution but I really don't know why this happens.

**Comment by maxhu08** [comment] 2024-11-23 18:44
This issue seems to have been fixed on it's own, so I'm going to close this issue.

**Closed by maxhu08** 2024-11-23 18:44 UTC
Labels: bug
